version: '3.9'
services:
  app:
    build: .
    ports:
      - "8001:8000"
      - "8765:8765"
    volumes:
      - ./data:/app/data
      - ./index:/app/index
    environment:
      - DATA_DIR=/app/data
      - INDEX_DIR=/app/index
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8765
    command: ["python", "-m", "app.main"]
